-- 自動生成: scripts/generate-seed-series.js
-- race_series シードデータ（シリーズマスタ）

INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('aomori-sakura-marathon', 'あおもり桜マラソン', 'Aomori Sakura Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('beppu-oita-marathon', '別府大分毎日マラソン', 'Beppu-Oita Mainichi Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('biwako-marathon', 'びわ湖マラソン', 'Biwako Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('challenge-fuji5lakes', 'チャレンジ富士五湖ウルトラマラソン', 'Challenge Fuji Five Lakes Ultra Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('ehime-marathon', '愛媛マラソン', 'Ehime Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('fujisan-marathon', '富士山マラソン', 'Mt. Fuji Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('fukui-sakura-marathon', 'ふくい桜マラソン', 'Fukui Sakura Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('fukuoka-international-marathon', '福岡国際マラソン', 'Fukuoka International Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('gunma-marathon', 'ぐんまマラソン', 'Gunma Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('himeji-castle-marathon', '世界遺産姫路城マラソン', 'World Heritage Himeji Castle Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('hofu-yomiuri-marathon', '防府読売マラソン', 'Hofu Yomiuri Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('hokkaido-marathon', '北海道マラソン', 'Hokkaido Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('ibusuki-nanohana', 'いぶすき菜の花マラソン', 'Ibusuki Nanohana Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('itabashi-city-marathon', '板橋Cityマラソン', 'Itabashi City Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('iwaki-sunshine-marathon', 'いわきサンシャインマラソン', 'Iwaki Sunshine Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('iwate-oshu-kirameki-marathon', 'いわて奥州きらめきマラソン', 'Iwate Oshu Kirameki Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kagawa-marathon', 'かがわマラソン', 'Kagawa Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kagoshima-marathon', '鹿児島マラソン', 'Kagoshima Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kanazawa-marathon', '金沢マラソン', 'Kanazawa Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kasumigaura-marathon', 'かすみがうらマラソン', 'Kasumigaura Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('katsuta-marathon', '勝田全国マラソン', 'Katsuta National Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kitakyushu-marathon', '北九州マラソン', 'Kitakyushu Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kix-senshu-marathon', 'KIX泉州国際マラソン', 'KIX Senshu International Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kobe-marathon', '神戸マラソン', 'Kobe Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kochi-ryoma-marathon', '高知龍馬マラソン', 'Kochi Ryoma Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kumamoto-castle-marathon', '熊本城マラソン', 'Kumamoto Castle Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('kyoto-marathon', '京都マラソン', 'Kyoto Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('matsumoto-marathon', '松本マラソン', 'Matsumoto Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('mie-matsusaka-marathon', 'みえ松阪マラソン', 'Mie Matsusaka Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('mito-komon-manyu-marathon', '水戸黄門漫遊マラソン', 'Mito Komon Manyu Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('nagano-marathon', '長野マラソン', 'Nagano Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('nagoya-womens-marathon', '名古屋ウィメンズマラソン', 'Nagoya Women''s Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('naha-marathon', 'NAHAマラソン', 'NAHA Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('nara-marathon', '奈良マラソン', 'Nara Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('nishio-marathon', 'にしおマラソン', 'Nishio Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('okayama-marathon', 'おかやまマラソン', 'Okayama Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('osaka-marathon', '大阪マラソン', 'Osaka Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('sado-toki-marathon', '佐渡トキマラソン', 'Sado Toki Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('saga-sakura-marathon', 'さが桜マラソン', 'Saga Sakura Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('saitama-marathon', 'さいたまマラソン', 'Saitama Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('shizuoka-marathon', '静岡マラソン', 'Shizuoka Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('shonan-international-marathon', '湘南国際マラソン', 'Shonan International Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('soja-kibiji-marathon', 'そうじゃ吉備路マラソン', 'Soja Kibiji Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tamba-sasayama-abc-marathon', '丹波篠山ABCマラソン', 'Tamba-Sasayama ABC Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tateyama-wakashio', '館山若潮マラソン', 'Tateyama Wakashio Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tokushima-marathon', 'とくしまマラソン', 'Tokushima Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tokyo-marathon', '東京マラソン', 'Tokyo Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tottori-marathon', '鳥取マラソン', 'Tottori Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('toyako-marathon', '洞爺湖マラソン', 'Lake Toya Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('toyama-marathon', '富山マラソン', 'Toyama Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('tsukuba-marathon', 'つくばマラソン', 'Tsukuba Marathon');
INSERT OR IGNORE INTO race_series (id, name_ja, name_en) VALUES ('yokohama-marathon', '横浜マラソン', 'Yokohama Marathon');
